# for development
version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: deanoffice
    volumes:
       - ./db-data:/data/postgres
       - ./dumps:/dump
    ports:
      - "5432:5432"
    restart: unless-stopped
